
###################################################################
#
#    a simple script for splitting fasta file and rename them
#
#    and  convert them to .ali format
#
###################################################################


# author: yanhong hong

id="$1"
dirname1="obsolete"
filename1="non_template.txt"

csplit -s $1 '/>/' '{*}'

rm xx00

ls xx* > origlist

cat xx*|grep ">"|cut -d"|" -f2 > genenamelist

paste origlist genenamelist |tr [:blank:] "," > renamelist

rm origlist genenamelist

while IFS=',' read orig target; do mv --backup=numbered  "$orig" "$target.fasta"; done < renamelist

rm renamelist

# remove files or directories that may be generated by the previous run.

if [[ -d ${dirname1} ]]
then
	rm -rf ${dirname1}
fi

if [[ -e ${filename1} ]]
then
	rm -rf ${filename1}
fi


for i in *.fasta
do
	if   [ "$i"  != "$1" ]
	then
		rm -rf `basename $i .fasta`
		mkdir `basename $i .fasta`
		mv $i `basename $i .fasta`
		echo ">P1;"`basename $i .fasta` >> `basename $i .fasta`/`basename $i .fasta`.ali
		echo "sequence:"`basename $i .fasta`":::::::0.00: 0.00" >> `basename $i .fasta`/`basename $i .fasta`.ali
		cat `basename $i .fasta`/$i|awk 'NR > 1' >> `basename $i .fasta`/`basename $i .fasta`.ali
		truncate -s -1 `basename $i .fasta`/`basename $i .fasta`.ali
		echo  "*" >> `basename $i .fasta`/`basename $i .fasta`.ali
		echo "`basename $i .fasta`"
	fi
done


